### ISSUE TITLE
DBUnit 2.4.9 needs java 6 to run

### ISSUE THREAD

**Issue by jeffjensen** [dbunit/dbunit-extension#541]
> **Migrated from SourceForge** — [Bugs #340](https://sourceforge.net/p/dbunit/bugs/340/)
> Originally reported by **djeanprost** on 2013-01-08 10:11:34.474000
> Priority: `5`
> Labels: java 6
> Assigned to **jeffjensen**
> SF status: closed-accepted
> Closed on 2014-04-20 02:59:08.802000

After migrating from 2.4.7 to 2.4.9, I get the following exception which is a consequence of http://sourceforge.net/p/dbunit/feature-requests/174/ I guess. 
I'm running using java5.

java.lang.NoSuchMethodError: java.lang.String.isEmpty()Z
	at org.dbunit.ext.mssql.UniqueIdentifierType.getSqlValue(UniqueIdentifierType.java:54)
	at org.dbunit.database.ForwardOnlyResultSetTable.getValue(ForwardOnlyResultSetTable.java:104)
	at org.dbunit.dataset.DefaultTable.addTableRows(DefaultTable.java:139)
	at org.dbunit.database.CachedResultSetTable.<init>(CachedResultSetTable.java:69)
	at org.dbunit.database.CachedResultSetTableFactory.createTable(CachedResultSetTableFactory.java:52)
	at org.dbunit.database.AbstractDatabaseConnection.createQueryTable(AbstractDatabaseConnection.java:90)
	at com.toto.affaires.revisioncdg.repositories.RepositoryRevisionCDGImplTest.testCreerRevisionCDG(RepositoryRevisionCDGImplTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:592)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

---

**jeffjensen** — 2014-04-19 23:06:17.028000
Changed code for Java 5, for next release after 2.4.9.
