### ISSUE TITLE
Is not working with EXML 7.0

### ISSUE THREAD

**Issue by jeffjensen** [dbunit/dbunit-extension#84]
> **Migrated from SourceForge** — [Bugs #39](https://sourceforge.net/p/dbunit/bugs/39/)
> Originally reported by **andreipavlenko** on 2003-08-15 13:39:51
> Priority: `5`
> Labels: Bug
> Assigned to **mlaflamm**
> SF status: closed-fixed
> Closed on 2008-06-14 08:21:29

1\. If I set classpath like this
dbunit.jar;exml.jar\(dbunit\);exml.jar\(EXML 7.0\) than
Glue \(ver. 4.1.2\) is not working.

Glue Error message:
java.lang.RuntimeException:
java.lang.NoSuchMethodError:
electric.xml.Document.&amp;lt;init&amp;gt;\(\[BI\)V
	at
electric.util.product.Product.startupAsServer\(Unknown
Source\)
	at
electric.util.product.Product.startupAsServer\(Unknown
Source\)
	at electric.server.http.HTTP.startup\(Unknown Source\)
	at electric.server.http.HTTP.startup\(Unknown Source\)
	at com.ipad.server.Launcher.main\(Launcher.java:17\)
Exception in thread &amp;quot;main&amp;quot;

2\. On other hand, if I set classpath
dbunit.jar;exml.jar\(EXML 7.0\);exml.jar\(dbunit\) than
DBUnit is not working.

DBUnit Error Message:
junit.framework.TestSuite@e79839java.lang.VerifyError:
\(class: org/dbunit/dataset/xml/XmlDataSet, method:
getTables signature:
\(Lelectric/xml/Document;\)\[Lorg/dbunit/dataset/ITable;\)
Incompatible object argument for function call

---

**mlaflamm** — 2003-08-16 02:06:43
Logged In: YES 
user\_id=466344

You are right DbUnit is not working with EXML 4.0 or later. 
Please try the current CVS repository version, which is using 
SAX2 \(via JAXP\) as XML parser instead of EXML.

**mlaflamm** — 2004-01-23 06:38:59
Logged In: YES 
user\_id=466344

DbUnit 2.0 is not using Electric XML anymore but SAX2.
